spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
cache:
  type:
    local: guava
    distribute: redis

distribute:
  type:
    enable: true
    # single or cluster
    arrange: single
    lock: redisson
    semaphore: redisson
